CREATE DATABASE SALES_ANALYSIS;

USE SALES_ANALYSIS;

SELECT * FROM SALES_TABLE;

SELECT SUM(TOTAL_AMOUNT) FROM SALES_TABLE;


SELECT * FROM ORDERS_DATA;

SELECT * FROM PRODUCTS;

SELECT * FROM CUSTOMERS;

# TOP 5 PRODUCTS BY TOTAL SALES

#SELECT CURRENT_DATE AS TODAY_DATE;

#SELECT NOW()

DESCRIBE SALES_TABLE;


DESC SALES_TABLE;

ALTER TABLE SALES_TABLE ADD COLUMN ORDER_DATE_NEW DATE;

UPDATE SALES_TABLE
SET ORDER_DATE_NEW = STR_TO_DATE(ORDER_DATE, "%d-%m-%Y");

ALTER TABLE SALES_TABLE DROP COLUMN ORDER_DATE;

DESC SALES_TABLE;

ALTER TABLE SALES_TABLE RENAME COLUMN ORDER_DATE_NEW TO ORDER_DATE;


SELECT ORDER_DATE,DAY(ORDER_DATE),MONTH(ORDER_DATE)AS MONTH
FROM SALES_TABLE;

SELECT MONTHNAME(ORDER_DATE) AS MONTH FROM SALES_TABLE;

SELECT CUSTOMER_ID,CUSTOMER_NAME,DAY(ORDER_DATE),MONTHNAME(ORDER_DATE) AS DAY FROM SALES_TABLE;

SELECT CUSTOMER_ID,DAYNAME(ORDER_DATE),MONTHNAME(ORDER_DATE)  FROM SALES_TABLE;

SELECT EXTRACT(MONTH FROM ORDER_DATE) FROM SALES_TABLE;

SELECT CUSTOMER_ID , COUNT(ORDER_ID) FROM ORDERS_DATA
GROUP BY CUSTOMER_ID;

SELECT COUNT(ORDER_ID) FROM ORDERS_DATA;

SELECT COUNT(DISTINCT ORDER_ID) FROM ORDERS_DATA;



#1----TOP 5 PRODUCTS BY SALES:-

SELECT PRODUCT_NAME, SUM(TOTAL_AMOUNT) AS TOTAL_SALES FROM SALES_TABLE
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 5;


#2----Monthly Revenue Trend:-

SELECT 
    monthname(order_date),month(order_date) AS month,year(order_date) as year,
    sum(total_amount) AS revenue
FROM sales_table
GROUP BY monthname(order_date),year(order_date),month(order_date)
ORDER BY month;


#3----City-wise Revenue:-

SELECT CITY, SUM(TOTAL_AMOUNT) AS REVENUE
FROM SALES_TABLE 
GROUP BY CITY
ORDER BY REVENUE DESC;


#4----Customer Who Spent the Most:-

SELECT CUSTOMER_NAME, SUM(TOTAL_AMOUNT) AS TOTAL_SPENT FROM SALES_TABLE
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 1;


#5----Category-wise Average Order Value:-

-- SELECT CATEGORY , AVG(TOTAL_AMOUNT) AS AOV
-- FROM SALES_TABLE
-- GROUP BY CATEGORY;

SELECT CATEGORY , SUM(TOTAL_AMOUNT) * 1.0 / COUNT(DISTINCT ORDER_ID) AS AOV
FROM SALES_TABLE
GROUP BY CATEGORY
ORDER BY AOV DESC;


#6----Most Frequent Buyer:-

SELECT CUSTOMER_ID ,COUNT(ORDER_ID) AS TOTAL_ORDERS FROM sales_table
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_ORDERS DESC
LIMIT 1;

SELECT * FROM CUSTOMERS
WHERE CUSTOMER_ID = 32;


#7---- Running Total of Revenue:-
SELECT  ORDER_DATE, SUM(TOTAL_AMOUNT) OVER(ORDER BY ORDER_DATE)  AS RUNNING_TOTAL
FROM SALES_TABLE;


#8----Rank Products by Sales-

SELECT PRODUCT_NAME , SUM(TOTAL_AMOUNT) AS TOTAL_SALE
FROM SALES_TABLE
GROUP BY PRODUCT_NAME
ORDER BY  TOTAL_SALE DESC
LIMIT 5;

SELECT PRODUCT_NAME , SUM(TOTAL_AMOUNT) AS TOTAL_SALES,
RANK() OVER(ORDER BY SUM(TOTAL_AMOUNT) DESC) AS SALES_RANK
FROM SALES_TABLE
GROUP BY PRODUCT_NAME;





